name: ci-tgbot.yml
on:
  # Run this workflow every time a new commit pushed to upstream/fork repository.
  # Run workflow on fork repository will help contributors find and resolve issues before sending a PR.
  push:
    # Exclude branches created by Dependabot to avoid triggering current workflow
    # for PRs initiated by Dependabot.
    branches-ignore:
      - 'dependabot/**'
    paths:
      - 'tgbot/**'       # only be triggered for specific folders
  pull_request:
    branches:
      - main
    paths:
      - 'tgbot/**'       # only be triggered for specific folders
jobs:
  build-and-push-image:
    name: build and push image
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: warjiang/tgbot
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      - name: detect misc info
        id: misc
        run: |
          echo "os=$(go env GOHOSTOS)" >> $GITHUB_OUTPUT
          echo "arch=$(go env GOHOSTARCH)" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "platforms=$PLATFORMS" >> $GITHUB_OUTPUT
      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push image
        uses: docker/build-push-action@v6
        with:
          file: "tgbot/Dockerfile"
          context: "tgbot"
          push: true
          tags: ${{ steps.misc.outputs.image_name }}:latest
          platforms: ${{ steps.misc.outputs.platforms }}